# Generated by Django 5.2.5 on 2025-08-19 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_key', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(blank=True, max_length=12, null=True)),
                ('coat_color', models.CharField(blank=True, max_length=255, null=True)),
                ('father_key', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_key', models.CharField(blank=True, max_length=10, null=True)),
                ('relatives', models.CharField(blank=True, max_length=255, null=True)),
                ('prize', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_key', models.CharField(blank=True, max_length=8, null=True)),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_key', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'kdb_horse',
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'kdb_jockey',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=12)),
                ('race_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('debut', models.BooleanField(default=False)),
                ('race_class', models.CharField(max_length=255)),
                ('surface', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
                ('track_condition', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('start_at', models.CharField(blank=True, max_length=255)),
                ('venue_code', models.CharField(max_length=255)),
                ('venue', models.CharField(db_index=True, max_length=255)),
                ('lap', models.CharField(max_length=255)),
                ('pace', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kdb_race',
            },
        ),
        migrations.CreateModel(
            name='Stallion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_key', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('father_key', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_key', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('prize', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer_key', models.CharField(blank=True, max_length=7, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_key', models.CharField(blank=True, max_length=8, null=True)),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_key', models.CharField(blank=True, max_length=7, null=True)),
                ('race_text', models.CharField(blank=True, max_length=255, null=True)),
                ('relatives', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kdb_stallion',
            },
        ),
        migrations.CreateModel(
            name='HorseRacing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(default='', max_length=12)),
                ('horse_key', models.CharField(default='', max_length=10)),
                ('horse_number', models.IntegerField(default=0)),
                ('running_time', models.CharField(default='', max_length=255)),
                ('odds', models.FloatField(default=0.0)),
                ('passing_order', models.CharField(db_index=True, default='', max_length=255)),
                ('finish_position', models.IntegerField(db_index=True, default=0)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('weight_change', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('handicap', models.FloatField(default=0.0)),
                ('final_600m_time', models.FloatField(blank=True, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('race_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('details', models.TextField(default='')),
                ('debut', models.BooleanField(default=False)),
                ('race_class', models.CharField(default='', max_length=255)),
                ('surface', models.CharField(default='', max_length=255)),
                ('distance', models.IntegerField(default=0)),
                ('direction', models.CharField(default='', max_length=255)),
                ('track_condition', models.CharField(default='', max_length=255)),
                ('weather', models.CharField(default='', max_length=255)),
                ('start_at', models.CharField(blank=True, default='', max_length=255)),
                ('venue_code', models.CharField(default='', max_length=255)),
                ('venue', models.CharField(db_index=True, default='', max_length=255)),
                ('lap', models.CharField(default='', max_length=255)),
                ('pace', models.CharField(default='', max_length=255)),
                ('training_center', models.CharField(default='', max_length=4)),
                ('owner', models.CharField(default='', max_length=255)),
                ('farm', models.CharField(default='', max_length=255)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb.horse')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb.jockey')),
            ],
            options={
                'db_table': 'kdb_horseracing',
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_odds', models.JSONField(blank=True, null=True)),
                ('show_odds', models.JSONField(blank=True, null=True)),
                ('quinella_odds', models.JSONField(blank=True, null=True)),
                ('quinella_place_odds', models.JSONField(blank=True, null=True)),
                ('trio_odds', models.JSONField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb.race')),
            ],
            options={
                'db_table': 'kdb_odds',
            },
        ),
    ]
