# Generated by Django 5.2.5 on 2025-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odds',
            name='horse',
        ),
        migrations.AddField(
            model_name='horseracing',
            name='trainer_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
